### ISSUE TITLE
ACM release notes should follow the best practices

### ISSUE THREAD

**Issue by Disper** [kyma-project/application-connector-manager#103]
Currently we, and other teams are not following the same practices.

We need to align on what those would be.

**Comment by Disper** [comment]
@zhoujing2022 we've heard that you have something in mind about RN best practices. Could you share with us on how they should look like?

**Comment by zhoujing2022** [comment]
will send you something per chat.

**Comment by Disper** [comment]
I'm closing this one, we will use an internal tracking tool (with the same issue name) as there are some links attached that are not available outside of the SAP.
