### ISSUE TITLE
Enable Markdown link check to find any broken links

### ISSUE THREAD

**Issue by grego952** [kyma-project/application-connector-manager#106]
**Description**
The /kyma-project repositories in GitHub should use [Markdown link check](https://github.com/tcort/markdown-link-check) to check their Markdown files for broken links. 
We should configure this tool for the Application Connector Manager repo.

**Reasons**
It facilitates checking for broken links.

**Attachments**

**Comment by Disper** [comment]
Is it a duplicate of https://github.com/kyma-project/application-connector-manager/issues/42 ?
