### ISSUE TITLE
Add caching layer to central-application-gateway to improve performance

### ISSUE THREAD

**Issue by koala7659** [kyma-project/application-connector-manager#150]
**Description**
Application Gateway must cache Kubernetes API server calls to improve performance. The following objects data must be cached:

- Application CRD objects
- Credentials

Added by @tobiscr on 2024-06-28 : It has to be proven that the Applicaton Connector Module is able to process > 30 requests per seconds without causing client side throttling by the Kubernetes client.

**Reasons**
Some experiments were performed to understand the performance characteristics of the Application Gateway. Mock target API deployed inside Kubernetes cluster was used to measure operations performed by the Application Gateway. The experiments were performed with [ddosify](https://github.com/ddosify/ddosify) tool. 
 
Although Application Gateway uses Horizontal Autoscaling, the experiments revealed that the maximal number of request per second was much smaller than expected. Analysis shown that the problem is directly caused by long response time of Kubernetes API server calls.  

Added by @tobiscr on 2024-06-28: The ACM is also used by the SAP IT store which require a higher throughput (>30req/sec) and the currently used old application connector (Kyma 2.15) isn't able to deal with such load.

**Depends on**
#118  - if load test shows we are performing well, adding a caching layer could become obsolete

**Comment by tobiscr** [comment]
PR: https://github.com/kyma-project/application-connector-manager/pull
