### ISSUE TITLE
[Test Case] - Test the integrations with SAP systems

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/application-connector-manager#156]
**Description**

Implement tests integrating external Java application with Kyma. 

We do not have an automated test for testing such integrations and we want to track such scenarios.

**Reasons**

There are some integrations written in Java that are working with Kyma. The main reason is we want to make sure that we do not break any existing integrations.

**Comment by tobiscr** [comment]
Issue outdated, closing it
