### ISSUE TITLE
Check for K8s 1.28 compatiblity of AC module (#5057)

### ISSUE THREAD

**Issue by Disper** [kyma-project/application-connector-manager#194]
We have to ensure that AC works fine on a  Kubernetes 1.28 cluster.

We have to finalise the check before 20.03.2024

**Comment by koala7659** [comment]
We should perform two kinds of checks 

1) If the module operator is running correctly (module can be installed, removed, reconcilled) without any problems 

2) The component tests pass for all three services (validator, gateway, and runtime agent)

For more details see:  https://github.com/kyma-project/kyma/blob/main/tests/components/application-connector

**Comment by tobiscr** [comment]
AC was tested on K8s 1.28 by @mvshao  and works perfect!
