### ISSUE TITLE
The Compass Runtime Agent's pod should not require istio-system namespace to start

### ISSUE THREAD

**Issue by Disper** [kyma-project/application-connector-manager#221]
- Extend Application Connector CRD to add Runtime Agent parameters
 (can be done in parallel) The Compass Runtime Agent's pod should not require istio-system namespace to start (see https://github.com/kyma-project/kyma/issues/17698 for details) (@VOID404 )
 - Remove code from CRA https://github.com/kyma-project/kyma/pull/18628
 - Remove unused permissions from app conn manager https://github.com/kyma-project/application-connector-manager/pull/215
 code-review

**Linked issues**
- extracted from #48

**Comment by koala7659** [comment]
Migration code is removed. 

The topic will be continued in https://github.com/kyma-project/application-connector-manager/issues/160
