### ISSUE TITLE
App Connector Module - Implement setting of correct status of app-connector CR when Istio is missing

### ISSUE THREAD

**Issue by koala7659** [kyma-project/application-connector-manager#24]
**Description**

The application-connector-manager needs to detect if Istio is installed on the cluster during installation of application-connector. 

**Acceptance criteria**

If Istio is missing application-connector CR must be set to Error state, and provide the clear message what is missing.
After Istio is installed the application-connector-manager should resume installation.

**Comment by m00g3n** [comment]
As we agreed we will:
- add finalizers on `VirtualService` and `Gateway` CRs to prevent 
- make sure that the reconciliation will be on `15m` schedule

**Comment by m00g3n** [comment]
https://github.com/kyma-project/application-connector-manager/pull/44
