### ISSUE TITLE
ACM is using incompatible log-format for SAP Cloud Logging

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/application-connector-manager#242]
**Description**

Log messages from ACM send to SAP Cloud Logging cannot be properly processed because the `timestamp` attribute cannot be correctly parsed as a Date.

We should change the date format from `Apr 15 07:48:08.318392483` to `2024-04-15T07:48:26.000Z`.

**Expected result**

Log messaged send to SAP Cloud Logging use a date format which Cloud Logging can parse and convert to a date.

**Actual result**

Timestamp for log messages from ACM are causing conflicts because the provided date format is not compatible with the parsing rules of Cloud Logging.

**Steps to reproduce**

Collect the logs with SAP Cloud Logging and review the Logs of ACM: timestamp field will be dropped

**Troubleshooting**

**References**
An issue reported by internal Kyma Customer (see external link in project data).
When the issue is fixed, remember to resolve the customer issue too.

**Comment by a-thaler** [comment]
Fixed by linked PR of @shorim
