### ISSUE TITLE
App Connector Module - Include Compass Runtime Agent into application-connector module

### ISSUE THREAD

**Issue by koala7659** [kyma-project/application-connector-manager#27]
Include all charts of Compass Runtime Agent into yaml file of the application-connector Kyma module .

**Acceptance criteria**

- [x] Compass Runtime Agent should be running without errors as part of application-connector module.

**Comment by akgalwas** [comment]
Pick one of the following solutions:
- Only if secret with token is not available the Compass Runtime Agent yaml should be installed.
- CRA is installed no matter if the secret exists (make sure the CRA will connect to Compass once secret is created)

**Comment by akgalwas** [comment]
Mind how CRA is integrated with Compass Runtime Agent.

**Comment by koala7659** [comment]
PR: https://github.com/kyma-project/application-connector-manager/pull/28/files

**Comment by tobiscr** [comment]
@koala7659  - Isn't this a duplicate of #48 ?

**Comment by koala7659** [comment]
@tobiscr Yes, indeed!
