### ISSUE TITLE
Release ACM 1.1.8 which includes caching capabilities

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/application-connector-manager#317]
**Description**

Create a new ACM release which includes the latest changes.

AC:
- [x] Ensure no security findings exist
- [x] Ensure caching feature is included in the release
- [x] Prepare code for release
- [x] New release in GitHub
- [x] Make release notes
- [x] Release to dev channel
- [ ]  ~~Test on dev~~
- [x] Release to experimental channel
- [x] Test on stage - Commerce Integration
- [x] Paperwork with Joe **In Progress**
- [x] Release to fast channel **PR Ready to merge**
- [ ] Release to regular channel 
- [x] Fix HOWTO release documentation **PR in our documentation repo**

**Comment by Disper** [comment]
1.1.7 was put on hold, we have to release 1.1.8 because security vulns

**Comment by tobiscr** [comment]
Rollout steps will finally be managed as part of completing the Microdelivery issue for 1.1.8
