### ISSUE TITLE
Add categories to CRD of ACM (required by Kyma ADR)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/application-connector-manager#361]
**Description**

In ADR https://github.com/kyma-project/community/issues/912 we agreed to use categories in Kyma CRDs. The ACM is including a customer facing  CRD and categories has to be added to it.

AC:
- [ ] Add categories field to ACM's CDR as described in the Kyma ADR https://github.com/kyma-project/community/issues/912 (see section "Decsion")

**Reasons**

Be compliant with Kyma wide architectural requirements.

**Attachments**

**Comment by a-thaler** [comment]
Done

**Comment by tobiscr** [comment]
Many thanks @a-thaler !
